-- SHOPPTON-G68 : base Supabase
-- À exécuter dans Supabase > SQL Editor.
-- Cette configuration protège les données avec RLS.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text,
  weight text,
  price numeric(10,2) not null default 0,
  emoji text,
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  shop_name text not null default 'SHOPPTON-G68',
  contact text not null default '@shopptong68',
  subtitle text not null default 'Catalogue de produits légalement commercialisables',
  welcome text not null default 'Découvrez notre catalogue.',
  delivery text not null default 'Secteur 68'
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.settings enable row level security;

-- Lecture publique du catalogue.
drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products
for select using (active = true);

drop policy if exists "public read settings" on public.settings;
create policy "public read settings" on public.settings
for select using (true);

-- Seul un compte marqué admin peut modifier.
drop policy if exists "admin read all products" on public.products;
create policy "admin read all products" on public.products
for select using (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
);

drop policy if exists "admin insert products" on public.products;
create policy "admin insert products" on public.products
for insert with check (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
);

drop policy if exists "admin update products" on public.products;
create policy "admin update products" on public.products
for update using (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
) with check (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
);

drop policy if exists "admin delete products" on public.products;
create policy "admin delete products" on public.products
for delete using (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
);

drop policy if exists "admin update settings" on public.settings;
create policy "admin update settings" on public.settings
for update using (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
) with check (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
);

drop policy if exists "admin insert settings" on public.settings;
create policy "admin insert settings" on public.settings
for insert with check (
  exists(select 1 from public.profiles p where p.id=auth.uid() and p.is_admin=true)
);

-- Crée la ligne settings si elle n'existe pas.
insert into public.settings (shop_name,contact,subtitle,welcome,delivery)
select 'SHOPPTON-G68','@shopptong68','Catalogue de produits légalement commercialisables','Découvrez notre catalogue.','Secteur 68'
where not exists (select 1 from public.settings);

-- APRÈS avoir créé ton utilisateur admin dans Authentication > Users,
-- remplace TON_UUID par son UUID puis exécute :
-- insert into public.profiles (id,is_admin) values ('TON_UUID',true)
-- on conflict (id) do update set is_admin=true;
